proxy:
  image: traefik
  command: --web --docker --logLevel=WARN
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

app:
  build: .
  dockerfile: 'DockerfileDev'
  command: 'npm start'
  volumes:
    - '.:/app'
  environment:
    PORT: 8080
    VIRTUAL_HOST: 'media.*'
    FORCE_COLOR: 1
    AWS_ACCESS_KEY_ID:
    AWS_BUCKET:
    AWS_SECRET_ACCESS_KEY:
    S3_HOST:
    PUBLIC:
    FOLDER:
  links:
    - 'proxy:proxy'
  ports:
    - '8080'
  labels:
    - "traefik.frontend.rule=PathPrefix:/"

clientkit:
  build: './clientkit'
  command: 'dev'
  environment:
    FORCE_COLOR: 1
    NODE_ENV: development
  volumes:
    - './clientkit:/app/clientkit'
    - './views:/app/assets'
    - './public/_dist:/app/dist'
    - './rollup-cache:/app/rollup-cache'
