app:
  build: .
  command: 'npm run dev'
  volumes:
    - '.:/app'
    - '/app/node_modules'
  environment:
    PORT: 8080
    AWS_ACCESS_KEY: ''
    AWS_BUCKET: ''
    AWS_SECRET_ACCESS_KEY: ''
  ports:
    - '8080:8080'
