core:
  dist: '{{CWD}}/public/v2/_dist'
  assetPath: '{{CWD}}/public/v2'
  mobileFirst: false
  minify: false
  #fontParsingWhitelist: 'common.css'
  globalBabel: false
siteMaxWidth: '1600px'
docs:
  title: 'MediaManager'
  input: 'common.css'
  css:
    - '../common.css'
#stylesheets:
  #'common.css': '{{core.assetPath}}/common.css'
