debug: true
s3:
  Bucket: '{{ENV.BUCKET}}'
  SecretAccessKey: '{{ENV.SECRETKEY}}'
  AccessKeyId: '{{ENV.ACCESSKEY}}'
  Region: '{{ENV.REGION}}'
views:
  engines:
    html: 'handlebars'
  path: 'public'
plugins:
  vision:
    _priority: -1
  hapi-upload-s3:
    endpoint: '/api/media'
    s3Bucket: '{{s3.bucket}}'
    s3SecretAccessKey: '{{s3.secretaccesskey}}'
    s3AccessKeyId: '{{s3.accesskeyid}}'
    s3Region: '{{s3.region}}'
    contentTypes: ['image/jpeg']
