views:
  engines:
    njk: 'vision-nunjucks'
  path: '{{CWD}}/views'
  defaultExtension: 'njk'
  compileMode: 'async'
plugins:
  hapi-nunjucks-helpers:
    assets: 
      endpoint: '{{routePrefix}}/ui'
      mappingFile: '{{CWD}}/public/_dist/assets.json'
assets:
  path: 'public/_dist'
  endpoint: '/ui'
