debug: true
s3Host: "https://s3.amazonaws.com"
s3:
  bucket: '{{ENV.AWS_BUCKET}}'
  accessKey: '{{ENV.AWS_ACCESS_KEY_ID}}'
  secretAccessKey: '{{ENV.AWS_SECRET_ACCESS_KEY}}'
  region: '{{ENV.AWS_DEFAULT_REGION}}'
  profile: '{{ENV.AWS_PROFILE}}'

plugins:
  vision:
    _priority: -5
  hapi-upload-s3:
    bucket: '{{s3.bucket}}'
    accessKey: '{{s3.accessKey}}'
    secretAccessKey: '{{s3.secretAccessKey}}'
    region: '{{s3.region}}'
    profile: 'default'
